require("user.set")
require("user.plugins")
require("user.remap")

-- require plugins
require("user.plugin_config.barbar")
require("user.plugin_config.cmp")
require("user.plugin_config.lsp")
require("user.plugin_config.dashboard-nvim")
require("user.plugin_config.nvim-colorizer")
require("user.plugin_config.nvim-hardline")
require("user.plugin_config.scrollbar")
require("user.plugin_config.indent-blankline")
require("user.plugin_config.treesitter")
require("user.plugin_config.nvim-tree")
require("user.plugin_config.presence-nvim")
require("user.plugin_config.telescope")
require("user.plugin_config.todo-comments")
require("user.plugin_config.gitsigns")
require("user.plugin_config.toggleterm")
